'use client'
import Head from "next/head";
import WalletComponent from "@/components/WalletComponent";
import LoadWallet from "@/components/LoadWallet";
import { useContext } from "react";
import { WalletContext } from "@/contexts/WalletContext";

export default function createToken() {
  return (
    <>
      <Head>
        <title>Solana-Minter App</title>
        <meta name="description" content="Generated by create next app and " />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WalletComponent />
      </main>
    </>
  );
}
